name: verstka
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/arrow_back.png
    - assets/icons/check.png
  fonts:
    - family: MontserratAlternates
      fonts:
        - asset: assets/fonts/MontserratAlternates-Thin.ttf
          weight: 100
        - asset: assets/fonts/MontserratAlternates-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/MontserratAlternates-Light.ttf
          weight: 300
        - asset: assets/fonts/MontserratAlternates-Regular.ttf
          weight: 400
        - asset: assets/fonts/MontserratAlternates-Medium.ttf
          weight: 500
        - asset: assets/fonts/MontserratAlternates-Semibold.ttf
          weight: 600
        - asset: assets/fonts/MontserratAlternates-Bold.ttf
          weight: 700
        - asset: assets/fonts/MontserratAlternates-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/MontserratAlternates-Black.ttf
          weight: 900
